/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_.c
 * Generated on: Tue Aug 20 13:47:27 EET
 ********************************************************************/

#include "Rte_DoorSensorAbstractionSWC.h"

#include "string.h"


extern Rte_DE_my_uint8 ReadDoorSensor_PP_SR_DoorState;


const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC = &Rte_Instance_DoorSensorAbstractionSWC;




void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState (my_uint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
my_uint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
