/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_indication_SWC_.c
 * Generated on: Tue Aug 20 13:47:27 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorLock_indication_SWC.h"


extern const Rte_CDS_DoorLock_indication_SWC Rte_Instance_DoorLock_indication_SWC;
extern const Rte_CDS_DoorLock_indication_SWC * const Rte_Inst_DoorLock_indication_SWC;


extern Std_ReturnType DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;

extern FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState(my_uint8 DoorState)
{
	(Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value = DoorState;
}
DECLSPEC_EXPORT my_uint8* ARUnit_IWriteRef_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState(void)
{
	return &(Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT my_uint8 ARUnit_IRead_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState(void)
{
	return (Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT void ARUnit_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_ReturnCode(Std_ReturnType returnCode)
{
	DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch  delegate)
{
	Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_indication_SWC_DoorLock_indication_runnable(void)
{
	DoorLock_indication_runnable();
}
