/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indication_SWC_.c
 * Generated on: Tue Aug 20 13:47:27 EET
 ********************************************************************/

#include "Rte_DoorLock_indication_SWC.h"

#include "string.h"

Rte_DE_my_uint8 ReadDoorSensor_PP_SR_DoorState;
Rte_DE_my_uint8 DoorLock_indication_RP_SR_DoorState_DoorState;


const Rte_CDS_DoorLock_indication_SWC Rte_Instance_DoorLock_indication_SWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorLock_indication_SWC * const Rte_Inst_DoorLock_indication_SWC = &Rte_Instance_DoorLock_indication_SWC;


Std_ReturnType DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = 0;

my_uint8 Rte_IRead_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch (my_uint8 LedState)
{
	Std_ReturnType __result = DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(LedState);
	}
	Led_Switch_runnable(LedState);
	return __result;
}
